version: '3.7'
services:
  api_flask:
    container_name: api_flask
    build: ./flask_api
    environment:
      - CH_CLIENT_HOST=ch_server
      - CH_DB=real_data
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
    volumes:
      - ./flask_api/static:/static
    networks:
      - default
      - ch_ntw
    depends_on:
      - ch_client

  api_nginx:
    container_name: api_nginx
    build: ./nginx
    ports:
      - "5000:80"
      - "9443:9443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_flask

  ch_server:
    container_name: ch_server
    build: ./clickhouse
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=600
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
      - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
