version: '3.7'
services:
  api_flask:
    container_name: api_flask
    build: ./flask
  api_nginx:
    container_name: api_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_flask
